# Generated by Django 4.1.7 on 2023-02-25 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_description_menu_menu_item_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='menu_item_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
